// The lab catalog. Every lab lives in its own `labs/<id>/` directory, and
// `labs.json` lists them. That file is GENERATED from each lab's labspace.yaml
// (see scripts/catalog.mjs — served in dev / emitted at build by the Vite
// plugin, regenerated by the validator), so it's never hand-written and can't
// drift. One lab → the app enters it directly; several → a selection page.
//
// labs.json shape (generated):
//   {
//     "labs": [
//       {
//         "id": "tour-of-docker",              // directory name — keys saved state
//         "path": "labs/tour-of-docker/labspace.yaml",
//         "title": "A Tour of Docker",         // from labspace title / catalog.title
//         "description": "One-line summary.",  // from labspace description
//         "icon": "sailing",                   // material-symbols name
//         "tags": ["docker"],                  // chips
//         "estimatedMinutes": 30               // "~30 min" hint (or null)
//       }
//     ]
//   }
//
// Paths resolve relative to the app's base URL (like labspace.yaml does), so a
// subpath deploy (e.g. GitHub Pages /sbxlab/) just works.

/** URL of the catalog file, overridable with `?catalog=<path>`. */
export function resolveCatalogUrl() {
  const override = new URLSearchParams(window.location.search).get("catalog");
  return new URL(override || "labs.json", document.baseURI).toString();
}

function normalize(lab) {
  return {
    id: lab.id,
    title: lab.title || lab.id,
    description: lab.description || "",
    icon: lab.icon || "science",
    tags: Array.isArray(lab.tags) ? lab.tags : [],
    estimatedMinutes: lab.estimatedMinutes ?? null,
    // Raw tracking directive: false (opt-out), an overrides object, or null
    // (inherit the deployment default). Resolved against config.json at runtime.
    tracking: lab.tracking ?? null,
    // Fully-resolved URL of this lab's labspace.yaml, ready to hand to the loader.
    labspaceUrl: new URL(lab.path, document.baseURI).toString(),
  };
}

/**
 * Loads the catalog. Returns an array of normalized lab entries, or `null` when
 * no usable catalog exists (missing file, parse error, or empty list) so the
 * caller can fall back to single-lab mode.
 */
export async function loadCatalog(catalogUrl = resolveCatalogUrl()) {
  try {
    const res = await fetch(catalogUrl);
    if (!res.ok) return null; // no catalog -> Home shows a "no labs found" notice
    const data = await res.json();
    const labs = Array.isArray(data?.labs) ? data.labs : [];
    const valid = labs.filter((l) => l && l.id && l.path).map(normalize);
    return valid.length ? valid : null;
  } catch {
    // Malformed JSON or a network error: treat as "no catalog" and fall back.
    return null;
  }
}
